### ISSUE TITLE
html에 불필요한 코드가 있어 한번 말해봅니다.

### ISSUE THREAD

**Issue by goton10** [gmoj/fsgserver2#1]
게리모드 2018년 이후로 안하는 코딩하는 사람입니다.
어디서 많이 본 듯한 분인거 같아 한번 지적해봅니다.

모든 코드내 style요소에 내용을 중앙 정렬하는 코드가 불필요하게 들어가 있네요.

위 내용에 포함되는 코드를 모두 지우고 상단 style 태그내
```css
* {
    text-align: center;
}
```
를 추가해주시면 일일히 적지 않아도 됩니다.

또는 표준 태그는 아니지만 center 태그도 있으니 한번 고려해보세요

~~아니면 제가 html 제작기로 만든 html 파일에 대해 뭐라 한거 같나요.. ㅁㄴㅇ~~
